---
- name: Do something on CloudForms with Ansible
  hosts: localhost
  connection: local

  vars:
    api_uri: "https://192.168.42.135/api"
    # api_uri: "https://192.168.42.129/api"
    vm_name: "windows004"

  tasks:
    - debug: var=api_uri
    - debug: var=vm_name

    - name: Get CloudForms auth_token
      uri:
        url: "{{ api_uri }}/auth"
        method: GET
        validate_certs: no
        user: admin
        password: smartvm
        headers:
          accept: "application/json"
        return_content: yes
      register: token_output

    - set_fact: auth_token="{{ token_output.json.auth_token }}"
    - debug: var=auth_token

    - name: Get VM id
      uri:
        url: "{{ api_uri }}/vms?expand=resources&attributes=id&filter[]=name='{{ vm_name }}'"
        method: GET
        validate_certs: no
        headers:
          x-auth-token: "{{ auth_token }}"
          accept: "application/json"
        return_content: yes
      register: token_output

    - set_fact: vm_id="{{ token_output.json.resources[0].id }}"
    # - debug: var=token_output
    - debug: var=vm_id

    - name: SmartState the VM
      uri:
        url: "{{ api_uri }}/vms/{{ vm_id }}"
        method: POST
        validate_certs: no
        headers:
          x-auth-token: "{{ auth_token }}"
          accept: "application/json"
        body_format: json
        body:
          action: scan
        return_content: yes
      register: token_output

    - debug: var=token_output.json.message